### PR TITLE
🚧 initial version

### PR DESCRIPTION
**Pull request by gr2m**
### How it will work

1. Install the app: https://github.com/apps/rename-master-branch
2. For every repository that you install it on, the app will search&replace all occurrences of "master" with "main" and create a pull request. If it does not find any, it will still create a pull request with an empty commit in order to inform you that the search was performed successfully. 

   The pull request should also include about warnings for known frictions that are relevant to the current repository

   - GitHub pages is hard coded to be server from the `master` branch, unless it's configured to serve `gh-pages`
   - `semantic-release` has `"master"` hard-coded as a default branch, a custom [`branches` configuration](https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches) is required
   - The old version of Jenkins (https://mobile.twitter.com/jbjonesjr/status/1272700437905526786)
   - ... ?

3. When you merge that pull request, the app will 

   1. Create the "main" branch based on the latest commit in the default branch
   2. Updates the default branch in the repository
   3. Updates branch protections
   4. Update the base for all open pull requests
   5. Delete the previous default branch

4. ~~If something went wrong, use GitHub's <kdb>revert</kbd> feature. Once that pull request is merged, the app will revert the change to the previous default branch.~~ Unfortunately the revert feature will not work, because the pull request's base was `master`, which now no longer exists. And the base branch of a closed pull request cannot be changed, unfortunately.

   I will look into using a comment instead, e.g. `@rename-master-branch revert`

   The app can then recover the original default branch and settings. Once that is done, the `revert` button will re-occur on the pull request, so the user can revert the changes from the pull request. There is unfortunately no way to create a revert pull request via the API.

5. Uninstall the app once done.

For people who want to rename the default branch to something else, such as `latest`, `dev`, or `trunk`, I will create separate apps, so no configuration will be necessary.

### Architecture

- I will implement the GitHub App as a serverless app using [begin.com](https://begin.com/).
- Each GitHub App that is registered on GitHub will have a different webhook URL.
- When a webhook is received, it will get parsed and if it's an event we care about, I will use Begin's [Event Functions](https://docs.begin.com/en/event-functions/provisioning) for asynchronous handling
- On an github installation webhook event, I will load all repositories and create a separate "install" event for each
- For each of our own install event, I'll run the search & replace using https://github.com/gr2m/octokit-plugin-search-and-replace-pull-request/
- On a pull request webhook event, I'll check if the PR was created by the current app. If it was, I will create a an internal "rename" event. If the PR was from a `revert-*` branch, I will create an internal "revert" event instead.
- In the rename event handler, I will use https://github.com/gr2m/octokit-plugin-rename-branch to do the actual rename. I will store the repository id with its before/after default branch names and a timestamp for statistics and for the case of a revert

### CODE REVIEW

**Comment by dominguezcelada** [comment]
First of all, thanks a lot @gr2m for this effort and energy you are putting on this migration. Community needs more devs like you ❤️ 

---
Some feedback here:

> For people who want to rename the default branch to something else, such as latest, dev, or trunk, I will create separate apps, so no configuration will be necessary.

Would have more sense to be able to provide a config to the app so we only have one Github App to do the migration? (and maybe use `main` as default config value?). What do you think?

**Comment by gr2m** [comment]
> provide a config to the app

Configuring apps adds more friction. If the target branch name is the only difference then I think using different GitHub App registrations is more elegant. Note that there will be a single Node app handling all the registered GitHub Apps, just using different webhook event endpoint paths, such as `POST /webhooks/main`, `POST /webhooks/latest`, etc

**Comment by dominguezcelada** [comment]
> > provide a config to the app
> 
> Configuring apps adds more friction. If the target branch name is the only difference then I think using different GitHub App registrations is more elegant. Note that there will be a single Node app handling all the registered GitHub Apps, just using different webhook event endpoint paths, such as `POST /webhooks/main`, `POST /webhooks/latest`, etc

mmm... I guess it's fine if the amount of possible names is controlled (`latest`, `dev`, or `trunk`) is affordable but if users want more variations would become a bit annoying to create a Github App for every requested custom default branch name.

Also, to "reserve" on Github App's Marketplace could be a bit annoying (?).

**Comment by gr2m** [comment]
It's a problem when it's a problem :)

**Comment by gr2m** [comment]
I've created a CLI which basically does the same that the app will do, but manually:
https://github.com/rename-master-branch/github-cli

**Comment by gr2m** [comment]
Progress 
Kapture 2020-06-23 at 16 06 52

**Comment by gr2m** [comment]
that was closed by accident, continued in #2

**Pull request merged**
